### ISSUE TITLE
Does not merge nofollow properly on POST links

### ISSUE THREAD

**Issue by halo** [jvenezia/safe_target_blank#1]
Nice gem, thank you!

Unfortunately, links I create using `link_to method: :post` end up looking like this:

```
rel="["noopener", "noreferrer"] nofollow"
```

I realized that Rails adds `rel="nofollow"` [automagically](https://github.com/rails/rails/blob/9c35bf2a6a27431c6aa283db781c19f61c5155be/actionview/test/template/url_helper_test.rb#L373) by default for POST links  - I don't see where this is implemented though.

Also, if I may ask, would it not make sense to only add `noopener` when the URL is an external URL (starting with `http`) and not merely a relative path? What would be the security benefit of adding noopener to relative links?

Thank you for your time!

**Comment by halo** [comment]
Ah, [here it is](https://github.com/rails/rails/blob/9c35bf2a6a27431c6aa283db781c19f61c5155be/actionview/lib/action_view/helpers/url_helper.rb#L593) it takes your array and applies `#to_s` on it.

**Comment by jvenezia** [comment]
Thanks for the report, I'll take care of it soon.

**Comment by halo** [comment]
👋🏻

**Comment by dgilperez** [comment]
Hi! news?

**Comment by jvenezia** [comment]
Wow sorry for the delay. I'll try to have a look this weekend.

**Comment by dgilperez** [comment]
Thanks for responding @jvenezia! I went ahead and fixed the thing 🔝

**Comment by jvenezia** [comment]
Gem published!
https://rubygems.org/gems/safe_target_blank/versions/1.0.2
